### ISSUE TITLE
Reports of no galaxy being presented

### ISSUE THREAD

**Issue by chrislintott** [murraycu/android-galaxyzoo#12] opened 2014-12-23 21:22 UTC
1 user on Lollipop is reporting that the app loads and flashes, but does not display a galaxy.

**Comment by murraycu** [comment] 2015-01-15 09:42
Any chance of that user talking to me here?

**Comment by murraycu** [comment] 2015-02-06 08:05
I've seen this a couple of times after testing the app immediately after updating beta releases from the play store, though that's generally when I test it. It seems to be trying a cached subject, abandoning it, then trying the next, and not trying to download another when it has tried (and failed to load) them all. This abandoning-an-item behaviour is there to deal with cached subjects whose images have not been completely downloaded. Strangely, it seems to even lose its cached subjects that have already been classified and uploaded, suggesting a general problem with the sqlite database.

Restarting the app seems to fix the problem.

I've added some log output to the app and I've installed a log viewing app so I can investigate it more next time I see it.

**Comment by murraycu** [comment] 2015-02-23 09:57
I managed to reproduce this reliably by deleting the app's cache and then going back to the app and trying to load anothtr image - for instance, by clicking Invert or by finishing the classification.

So I think this was triggered by the Android system automatically deleting the app's cache to temporarily save space - Maybe that happens sometimes when installing app updates.

I'm confident that it's fixed now, but I will play with it a bit more here before releasing a new version.

**Comment by murraycu** [comment] 2015-02-25 09:12
I've just released version 1.38 with these fixes. Please let me know if the problem still happens.

**Closed by murraycu** 2015-02-25 09:12 UTC
